/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "discl_title": { "text": "Trikala Cinemas Widget", "view": "DC.Text" },
    "disclaimer": { "text": "Το πρόγραμμα (widget) κατασκευάστηκε για προσωπική χρήση και παρέχεται \"ως έχει\" χωρίς καμιά απολύτως εγγύηση οποιουδήποτε είδους. \nΠερισσότερες πληροφορίες:", "view": "DC.Text" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "scrollArea": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": 4 },
    "version": { "text": "Έκδοση v0.1 - 2011", "view": "DC.Text" }
};






