/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    dashcode.setupParts();
    startprog();
    //$('#box').html('');
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
    
    //Calculate time from previous refresh
    var now = Math.round((new Date().getTime())/1000);
    var previous_time=widget.preferenceForKey("timetominutessinceepoch");
    
    //Set time in order to "refresh" the page after 4 hours the least has past
    if ( now - previous_time > 14400) {
        startprog();
    }
    
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront");
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}

//Function that greps all the necessary data from page
function return_parse_data()
{
var teliko = new Array($('#result .field-content a[href*=cinema]').length);
var xaraktiristika = 9; //posa xaraktiristika theloyme na kratame

//cinemas - 0
$('#result .field-content a[href*=cinema]').each(function(index) {
        teliko[index] = new Array(xaraktiristika);
        teliko[index][0]=$(this).text();
});


//movies - 1
$('#result .views-field-title .field-content a[href*=movie]').each(function(index) {
        teliko[index][1]=$(this).text();
});

//ores provolon - 2
$('#result .views-field-field-session-times-value .field-content').each(function(index) {
    //teliko[index][2] = new Array($('.views-field-field-session-times-value .field-content').length);
 
    var ores = [];
 teliko[index][2] = null;
 
    $(this).children().each(function(index){
         ores[index] = $(this).text();  
     }); 
teliko[index][2] = ores.join("-");
 });

//eikones - 3
$('#result img').each(function(index) {
    teliko[index][3] = $(this).attr("src");  
 });

//diarkeia - 4
$('#result .views-field-field-length-value span').each(function(index) {
    teliko[index][4] = $(this).text();  
});

//date-start - 5
$('#result .date-display-start').each(function(index) {
    teliko[index][5] = $(this).text();   
});

//date-stop - 6
$('#result .date-display-end').each(function(index) {
    teliko[index][6] = $(this).text(); 
});

//cinema-address - 7
$('#result .views-field-field-address-value .field-content').each(function(index) {
     teliko[index][7] = $(this).text(); 
});

//cinema-tel - 8
$('#result .views-field-field-phone-info-value .field-content').each(function(index) {
     teliko[index][8] = $(this).text(); 
});

//movies-url - 9

$('#result .views-field-title .field-content a').each(function(index){
    teliko[index][9] = 'http://www.trikalacity.gr'+$(this).attr("href"); 
});
return teliko;
}

function putElementsInPlace(obj){
// Values you provide
var scrollAreaToChange = document.getElementById("scrollArea");	// replace with ID of scroll area to change

/*var newScrollAreaContent = '<div class="movie">
	<div class="cinema_name">'+obj[0][0]+'</div>
	<div class="cinema_name">'+obj[0][1]+'</div>
	<div class="poster_movie"><img src="'+obj[0][3]+'" height="180" width="120"></img></div>
	<div style="font-weight:bold; padding-top:5px;">Ώρες προβολής</div><div>'+obj[0][2]+'</div>
	<div style="font-weight:bold">Διάρκεια</div><div>'+obj[0][4]+'</div>
	<div>Από '+obj[0][5]+' έως '+obj[0][6]+'</div>
</div>
';
*/
var moreinfo = '<span style="font-weight:bold; font-family: Helvetica,Geneva,sans-serif; position: absolute; width: 120px; text-align: center; margin-top: 65px; display: none; font-size: 12px; color: #000000; padding-left:2px;">Δείτε περισσότερες πληροφορίες για την ταινία</span>';

scrollAreaToChange.object.content.innerHTML = "";
jQuery.each(obj, function(i) {
  scrollAreaToChange.object.content.innerHTML += '<div class="movie"><div class="cinema_name">'+obj[i][0]+'</div><div class="movie_name">'+obj[i][1]+'</div><div class="poster_movie"><a id="moviesurl" onclick="widget.openURL(\''+obj[i][9]+'\')" style="cursor:hand;">'+moreinfo+'<img src="'+obj[i][3]+'" height="180" width="120"></img></a></div><div style="font-weight:bold; padding-top:5px;">Ώρες προβολής</div><div>'+obj[i][2]+'</div><div><span style="font-weight:bold">Διάρκεια: </span>'+obj[i][4]+'</div><div>Από '+obj[i][5]+' έως '+obj[i][6]+'</div></div>';
});

scrollAreaToChange.object.refresh();


//Set time in order to "refresh" the page after 3 hours the least have past
var now = Math.round((new Date().getTime())/1000);
widget.setPreferenceForKey(now,"timetominutessinceepoch");

//MouveOver Images to display text to view movie details
$('a img').mouseout(function (){
    $(this).fadeTo('fast', 1, function() {
        $(this).prev().hide();
        $(this).prev().css("opacity","0");
    });
});
$('a img').mouseenter(function (){
    $(this).fadeTo('fast', 0.2, function() {
        $(this).prev().show();
        $(this).prev().css("opacity","1");
    });
});


}//putElementsInPlace

function startprog()
{
var url="http://www.trikalacity.gr/quicktabs/ajax/block/block_delta_18/1";

$.ajax({
   type: "GET",
   url: url,
   dataType: "text",
     success: function(msg){
        msg = "'"+msg+"'";
        msg = eval(msg);
        $('#result').html(msg);
        var teliko2 = return_parse_data();
        putElementsInPlace(teliko2);
    }//success
}); //ajax


       
}//startprog


